version: '2'

services:
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    # A Red Hat Customer Portal login is required to access this image. If you do not have one already, you can obtain one at https://www.redhat.com/wapps/ugc/register.html
    # Pull action should be successful from any RHEL Host system running the Docker service and executing the following command: docker login registry.connect.redhat.com
    # + info: https://access.redhat.com/containers/?tab=images&platform=docker#/registry.connect.redhat.com/bitnami/nodejs
    image: registry.connect.redhat.com/bitnami/nodejs
    # command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    volumes:
      - .:/app
